version: '3.8'

services:
  frontend:
    build:
      context: ..
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    environment:
      - FLASK_ENV=production
    ports:
      - "5001:5001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 