version: '3.8'

services:
  frontend:
    build:
      context: ..
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    # environment: # Environment variables should be managed via .env file
    #  - FLASK_ENV=production
    env_file:
      - ../backend/.env # Load .env file from the backend directory
    ports:
      - "5001:5001"
    volumes:
      - backend_logs:/app/logs
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    container_name: ad_password_reset_redis
    ports:
      - "6379:6379" # For external debugging, can be removed if not needed
    volumes:
      - redis_data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  backend_logs:
  redis_data: